dev:
  server:
    port: 8090
    firstSeed: false
    issuer: localhost
    accessToken:
      defaultFormat: jwt
      lifetime: 86400 # In Seconds
    refreshToken:
      lifetime: 86400 # In Seconds
  mongo:
    uri: mongodb://localhost
    username: admin
    password: pass
prod:
  server:
    port: 8090
    firstSeed: true
    issuer: localhost
    accessToken:
      defaultFormat: jwt
      lifetime: 86400 # In Seconds
    refreshToken:
      lifetime: 86400 # In Seconds
  mongo:
    uri: mongodb://localhost
    username: admin
    password: pass
